#! /bin/sh

#qsub -pe linux_smp_short 48-64 -N ene_recal -j y -o ~/Jobs -cwd  energy_recalculation_wrapper.sh

cd "$PWD"


#############claculating unresrtraint energies
inp_template='energy_recalculation.inp'

start=0.0
end=1.0

step=0.03125

win=`echo $start`
while [ $(echo " $win <= $end" | bc) -eq 1 ]; do
	
	echo $win
	sed s/XXXX/$win/g $inp_template > temp_fwd.inp
	sed s/XXXX/$win/g $inp_template > temp_bwd.inp
	sed -i s/YYYY/fwd/g  temp_fwd.inp
	sed -i s/YYYY/bwd/g  temp_bwd.inp
	namd2  temp_fwd.inp>! fwd_${win}.log
	namd2  temp_bwd.inp>! bwd_${win}.log
	win=$(echo  "$win+$step"|bc -l)
done

#############claculating restraint energies
win=0.0
inp_template='energy_restr_recalculation.inp'

sed s/XXXX/$win/g $inp_template > temp_fwd.inp
sed s/XXXX/$win/g $inp_template > temp_bwd.inp
sed -i s/YYYY/fwd/g  temp_fwd.inp
sed -i s/YYYY/bwd/g  temp_bwd.inp
namd2  temp_fwd.inp>! fwd_restr.log
namd2  temp_bwd.inp>! bwd_restr.log


